# Generated by Django 4.2.5 on 2023-09-14 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lettings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "address", "verbose_name_plural": "address"},
        ),
    ]
